using CountryLibrary.Countys;
using CountryLibrary.CountysLib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CountryLibrary
{
    public class NativeName
    {
        public Ara ara { get; set; }
        public Bre bre { get; set; }
        public Ces ces { get; set; }
        public Cym cym { get; set; }
        public Deu deu { get; set; }
        public Est est { get; set; }
        public Fin fin { get; set; }
        public Fra fra { get; set; }
        public Hrv hrv { get; set; }
        public Hun hun { get; set; }
        public Ita ita { get; set; }
        public Jpn jpn { get; set; }
        public Kor kor { get; set; }
        public Nld nld { get; set; }
        public Per per { get; set; }
        public Pol pol { get; set; }
        public Por por { get; set; }
        public Rus rus { get; set; }
        public Slk slk { get; set; }
        public Spa spa { get; set; }
        public Srp srp { get; set; }
        public Swe swe { get; set; }
        public Tur tur { get; set; }
        public Urd urd { get; set; }
        public Zho zho { get; set; }
        public Isl isl { get; set; }
        public Ltz ltz { get; set; }
        public Zdj zdj { get; set; }
        public Eng eng { get; set; }
        public Bel bel { get; set; }
        public Kin kin { get; set; }
        public Khm khm { get; set; }
        public Ell ell { get; set; }
        public Mfe mfe { get; set; }
        public Div div { get; set; }
        public Bis bis { get; set; }
        public Nya nya { get; set; }
        public Kat kat { get; set; }
        public Mri mri { get; set; }
        public Nzs nzs { get; set; }
        public Lao lao { get; set; }
        public Dan dan { get; set; }
        public Fao fao { get; set; }
        public Niu niu { get; set; }
        public Mkd mkd { get; set; }
        public Jam jam { get; set; }
        public Mey mey { get; set; }
        public Hmo hmo { get; set; }
        public Tpi tpi { get; set; }
        public Lit lit { get; set; }
        public Ron ron { get; set; }
        public Kir kir { get; set; }
        public Pap pap { get; set; }
        public Vie vie { get; set; }
        public Msa msa { get; set; }
        public Gsw gsw { get; set; }
        public Roh rho { get; set; }
        public Tha tha { get; set; }
        public Uzb uzb { get; set; }
        public Dzo dzo { get; set; }
        public Mah mah { get; set; }
        public Nno nno { get; set; }
        public Nob nob { get; set; }
        public Smi smi { get; set; }
        public Heb heb { get; set; }
        public Arc arc { get; set; }
        public Ckb ckb { get; set; }
        public Sot sot { get; set; }
        public Tvl tvl { get; set; }
        public Pus pus { get; set; }
        public Prs prs { get; set; }
        public Tuk tuk { get; set; }
        public Tir tir { get; set; }
        public Cat cat { get; set; }
        public Hye hye { get; set; }
        public Bar bar { get; set; }
        public Smo smo { get; set; }
        public Tkl tkl { get; set; }
        public Bjz bjz { get; set; }
        public Nrf nrf { get; set; }
        public Tsn tsn { get; set; }
        public Glv glv { get; set; }
        public Fas fas { get; set; }
        public Kal kal { get; set; }
        public Ben ben { get; set; }
        public Bos bos { get; set; }
        public Mlt mlt { get; set; }
        public Crs crs { get; set; }
        public Sin sin { get; set; }
        public Tam tam { get; set; }
        public Grn grn { get; set; }
        public Nor nor { get; set; }
        public Ukr ukr { get; set; }
        public Ber ber { get; set; }
        public Slv slv { get; set; }
        public Bwg bwg { get; set; }
        public Kck kck { get; set; }
        public Khi khi { get; set; }
        public Ndc ndc { get; set; }
        public Sna sna { get; set; }
        public Toi toi { get; set; }
        public Tso tso { get; set; }
        public Ven ven { get; set; }
        public Xho xho { get; set; }
        public Zib zib { get; set; }
        public Swa swa { get; set; }
        public Rar rar { get; set; }
        public Ind ind { get; set; }
        public Aym aym { get; set; }
        public Que que { get; set; }
        public Sag sag { get; set; }
        public Pov pov { get; set; }
        public Mon mon { get; set; }
        public Kon kon { get; set; }
        public Lin lin { get; set; }
        public Lua lua { get; set; }
        public Nau nau { get; set; }
        public Crn crn { get; set; }
        public Mya mya { get; set; }
        public Som som { get; set; }
        public Gle gle { get; set; }
        public Cha cha { get; set; }
        public Nep nep { get; set; }
        public Mlg mlg { get; set; }
        public Kaz kaz { get; set; }
        public Nfr nfr { get; set; }
        public Afr afr { get; set; }
        public Her her { get; set; }
        public Hgm hgm { get; set; }
        public Kwn kwn { get; set; }
        public Ndo ndo { get; set; }
        public Lat lat { get; set; }
        public Sqi sqi { get; set; }
        public Hat hat { get; set; }
        public Ton ton { get; set; }
        public Aze aze { get; set; }
        public Lav lav { get; set; }
        public Gil gil { get; set; }
        public Amh amh { get; set; }
        public Pau pau { get; set; }
        public Fij fij { get; set; }
        public Hif hif { get; set; }
        public Pih pih { get; set; }
        public Tgk tgk { get; set; }
        public Ssw ssw { get; set; }
        public Tet tet { get; set; }
        public Cal cal { get; set; }
        public Fil fil { get; set; }
        public Run run { get; set; }
        public Bul bul { get; set; }
        public Nbl nbl { get; set; }
        public Nso nso { get; set; }
        public Zul zul { get; set; }
        public Hin hin { get; set; }
       
    }
}
